# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '59 23 * * 0'

  # Allows you to run this workflow manually from the Actions tab
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: doy permisos de ejecución a gradlew
        run: chmod +x gradlew
      - name: Realiza la construcción
        run: ./gradlew build
      - name: Ejecuta los test
        run: ./gradlew test
      - name: Crea la documentación 
        run: ./gradlew javadoc
